"""
fix_report.py
=============
Patches an existing monthly_breakout_report.html generated by an older
version of monthly_macd_cci_breakout_screener.py.

Fixes applied:
  1. Adds STAGE_META and STAGE_SORT JS constants (missing → blank table)
  2. Adds Stage sort block in renderBody
  3. Adds Stage column render case (stage-badge)
  4. Adds stage-badge CSS classes
  5. Replaces ?? operator with || (browser compatibility)
  6. Replaces Infinity with 1e15 (sort stability)

Usage:
    python fix_report.py
    python fix_report.py --file path/to/monthly_breakout_report.html
"""
import argparse
import sys
from pathlib import Path

STAGE_META_JS = '''const STAGE_META = {
  "Stage 1A":{icon:"\\u25a1",label:"Stage 1A \\u2014 Early Base",    cls:"s1a"},
  "Stage 1B":{icon:"\\ud83d\\udd35",label:"Stage 1B \\u2014 Late Base",     cls:"s1b"},
  "Stage 2A":{icon:"\\ud83d\\udfe2",label:"Stage 2A \\u2014 Early Advance \\u2705",cls:"s2a"},
  "Stage 2B":{icon:"\\ud83d\\uddfe",label:"Stage 2B \\u2014 Mid Advance",   cls:"s2b"},
  "Stage 2C":{icon:"\\ud83d\\udfe1",label:"Stage 2C \\u2014 Late Advance \\u26a0\\ufe0f",cls:"s2c"},
  "Stage 3A":{icon:"\\ud83d\\udfe0",label:"Stage 3A \\u2014 Early Top",     cls:"s3a"},
  "Stage 3B":{icon:"\\ud83d\\udd34",label:"Stage 3B \\u2014 Distribution",  cls:"s3b"},
  "Stage 4A":{icon:"\\u2b1b",label:"Stage 4A \\u2014 Early Decline",  cls:"s4a"},
  "Stage 4B":{icon:"\\ud83d\\udfe3",label:"Stage 4B \\u2014 Capitulation",  cls:"s4b"},
};
const STAGE_SORT = {"Stage 1A":1,"Stage 1B":2,"Stage 2A":3,"Stage 2B":4,"Stage 2C":5,"Stage 3A":6,"Stage 3B":7,"Stage 4A":8,"Stage 4B":9};'''

STAGE_CSS = '''.stage-badge {
  padding: 2px 8px; border-radius: 10px; font-size: 0.76rem; font-weight: 700;
  white-space: nowrap; display: inline-block;
}
.s1a { background:#eceff1; color:#546e7a; }
.s1b { background:#e3f2fd; color:#1565c0; border:1px solid #90caf9; }
.s2a { background:#e8f5e9; color:#1b5e20; border:1px solid #a5d6a7; font-weight:800; }
.s2b { background:#c8e6c9; color:#2e7d32; border:1px solid #81c784; }
.s2c { background:#fff3e0; color:#e65100; border:1px solid #ffcc80; }
.s3a { background:#fbe9e7; color:#bf360c; border:1px solid #ffab91; }
.s3b { background:#ffebee; color:#b71c1c; border:1px solid #ef9a9a; }
.s4a { background:#f3e5f5; color:#4a148c; border:1px solid #ce93d8; }
.s4b { background:#ede7f6; color:#6a1b9a; border:1px solid #b39ddb; }'''

STAGE_RENDER_CASE = '''        case "Stage": {
          if(!v) return '<td>\u2013</td>';
          var stMeta = STAGE_META[v] || {icon:"\u25a1",label:v,cls:"s1a"};
          return '<td><span class="stage-badge ' + stMeta.cls + '" title="' + stMeta.label + '">' + stMeta.icon + ' ' + v + '</span></td>';
        }'''


def patch(html: str) -> tuple[str, list[str]]:
    applied = []

    # ── Fix 1: ?? operator → || ──────────────────────────────────────────────
    if '??9' in html or '??0' in html:
        html = html.replace('??9', '||9').replace('??0', '||0')
        applied.append("Fixed ?? operator → ||")

    # ── Fix 2: Infinity in sort ───────────────────────────────────────────────
    if 'sortAsc ? Infinity : -Infinity' in html:
        html = html.replace('sortAsc ? Infinity : -Infinity', 'sortAsc ? 1e15 : -1e15')
        applied.append("Fixed Infinity → 1e15 in sort")

    # ── Fix 3: Add STAGE_META + STAGE_SORT after TREND_CLS ───────────────────
    marker = 'const TREND_CLS'
    if 'STAGE_SORT' not in html and marker in html:
        # Find end of TREND_CLS line
        idx = html.find(marker)
        end = html.find('\n', idx) + 1
        html = html[:end] + STAGE_META_JS + '\n' + html[end:]
        applied.append("Added STAGE_META and STAGE_SORT constants")

    # ── Fix 4: Add Stage sort block in renderBody ─────────────────────────────
    if 'sortKey==="Stage"' not in html and 'sortKey==\\"Stage\\"' not in html:
        trend_sort = 'if (sortKey==="Trend_State")'
        if trend_sort in html:
            # Find end of Trend_State sort block
            idx = html.find(trend_sort)
            # Find the closing brace of this if block
            brace_end = html.find('\n    }', idx) + 6
            stage_sort_block = '''
    if (sortKey==="Stage") {
      var sa=STAGE_SORT[a.Stage]||99, sb=STAGE_SORT[b.Stage]||99;
      return sortAsc ? sa-sb : sb-sa;
    }'''
            html = html[:brace_end] + stage_sort_block + html[brace_end:]
            applied.append("Added Stage sort block in renderBody")

    # ── Fix 5: Add stage-badge CSS ────────────────────────────────────────────
    if '.stage-badge' not in html:
        # Insert before .super-badge or before </style>
        for anchor in ['.super-badge {', '.super-badge{', '</style>']:
            if anchor in html:
                html = html.replace(anchor, STAGE_CSS + '\n' + anchor, 1)
                applied.append("Added stage-badge CSS classes")
                break

    # ── Fix 6: Add Stage render case in switch(col) ───────────────────────────
    if 'case "Stage":' not in html:
        # Insert before Super_Bullish case
        for anchor in ['case "Super_Bullish":', "case 'Super_Bullish':"]:
            if anchor in html:
                html = html.replace(anchor,
                    STAGE_RENDER_CASE + '\n\n        ' + anchor, 1)
                applied.append("Added Stage column render case")
                break

    return html, applied


def main():
    parser = argparse.ArgumentParser(description="Patch monthly_breakout_report.html")
    parser.add_argument("--file", default="monthly_breakout_report.html",
                        help="Path to the HTML report file (default: monthly_breakout_report.html)")
    parser.add_argument("--inplace", action="store_true", default=True,
                        help="Overwrite the original file (default: True)")
    args = parser.parse_args()

    path = Path(args.file)
    if not path.exists():
        print(f"ERROR: File not found: {path}")
        sys.exit(1)

    print(f"Reading: {path} ({path.stat().st_size:,} bytes)")
    html = path.read_text(encoding="utf-8")

    patched, applied = patch(html)

    if not applied:
        print("Nothing to fix — file is already up to date.")
        return

    # Write backup
    backup = path.with_suffix(".html.bak")
    path.rename(backup)
    print(f"Backup saved: {backup}")

    # Write patched file
    path.write_text(patched, encoding="utf-8")
    print(f"Patched: {path} ({path.stat().st_size:,} bytes)")
    print()
    print("Fixes applied:")
    for f in applied:
        print(f"  ✓ {f}")
    print()
    print("Done! Open the HTML file in your browser.")


if __name__ == "__main__":
    main()
